{{/*
Copyright © 2025 Zubin Qayam — ZQAutoNXG Powered by ZQ AI LOGIC
Licensed under the Apache License, Version 2.0
*/}}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zqautonxg.fullname" . }}-postgres
  labels:
    {{- include "zqautonxg.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc }}
{{- end }}
