{{/*
Copyright © 2025 Zubin Qayam — ZQAutoNXG Powered by ZQ AI LOGIC
Licensed under the Apache License, Version 2.0
*/}}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zqautonxg.fullname" . }}-postgres
  labels:
    {{- include "zqautonxg.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "zqautonxg.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
