{{/*
Copyright © 2025 Zubin Qayam — ZQAutoNXG Powered by ZQ AI LOGIC
Licensed under the Apache License, Version 2.0
*/}}
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zqautonxg.fullname" . }}
  labels:
    {{- include "zqautonxg.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
