{{/*
Copyright © 2025 Zubin Qayam — ZQAutoNXG Powered by ZQ AI LOGIC
Licensed under the Apache License, Version 2.0
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zqautonxg.fullname" . }}
  labels:
    {{- include "zqautonxg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zqautonxg.selectorLabels" . | nindent 4 }}
